<?php
$auto_reviews_ship = array(
    array("name" => "Paweł H.", "text" => "Nie musiałem długo czekać, dostawa została zrealizowana profesjonalnie."),
    array("name" => "Michał M.", "text" => "Dostawa była wyjątkowo szybka, a wszystkie informacje otrzymałem mailowo i SMS-em. Szczególnie spodobało mi się to, że kurier zadzwonił przed przyjazdem. Wszystko było świetnie zorganizowane z myślą o kliencie."),
    array("name" => "Andrzej P.", "text" => "Wszystko dotarło na czas, kurier bardzo uprzejmy."),
    array("name" => "Krzysztof W.", "text" => "Opakowanie naprawdę solidne, widać dbałość o szczegóły."),
    array("name" => "Tomasz K.", "text" => "Paczka dotarła nienaruszona i była bardzo dobrze zapakowana. Wszystko odpowiednio zabezpieczone, zero ryzyka uszkodzeń. Duże brawa za profesjonalizm."),
    array("name" => "Marcin C.", "text" => "Usługa dostawy bez żadnych zastrzeżeń."),
    array("name" => "Piotr T.", "text" => "Kurier był uprzejmy i punktualny co do minuty. Paczka starannie zapakowana i bez uszkodzeń. Jestem bardzo zadowolony."),
    array("name" => "Grzegorz T.", "text" => "Bardzo szybka dostawa i świetna koordynacja."),
    array("name" => "Robert S.", "text" => "Obsługa na wysokim poziomie, wszystko jasno przekazane."),
    array("name" => "Mateusz O.", "text" => "Opakowanie było bardzo estetyczne i bezpieczne. Brak jakichkolwiek uszkodzeń, dostawa na umówiony termin. Same pochwały."),
    array("name" => "Jerzy J.", "text" => "Starannie zapakowane i bezpiecznie dostarczone."),
    array("name" => "Łukasz R.", "text" => "Paczka dotarła wcześniej niż planowano."),
    array("name" => "Adam B.", "text" => "Wszystko dotarło szybciej, niż się spodziewałem."),
    array("name" => "Kamil C.", "text" => "Dostawa była punktualna i szybka."),
    array("name" => "Jerzy U.", "text" => "Dostawa szybka, a opakowanie bardzo estetyczne. Obsługa klienta dostępna nawet poza godzinami pracy. Polecam każdemu."),
    array("name" => "Rafał C.", "text" => "Opakowanie schludne i solidne."),
    array("name" => "Sebastian R.", "text" => "Obsługa klienta szybko odpowiedziała na pytanie o termin dostawy. Paczka dotarła nawet wcześniej niż podano. Zdecydowanie polecam."),
    array("name" => "Krzysztof L.", "text" => "Bardzo prosty proces odbioru."),
    array("name" => "Łukasz P.", "text" => "Szybka dostawa i łatwy odbiór."),
    array("name" => "Daniel S.", "text" => "Bardzo dobra obsługa."),
    array("name" => "Marek H.", "text" => "Od momentu zamówienia do dostawy wszystko przebiegło bezproblemowo. Miałem stały wgląd w status przesyłki, co budowało zaufanie."),
    array("name" => "Paweł V.", "text" => "Dostawa była szybka."),
    array("name" => "Filip P.", "text" => "Paczka dotarła w ciągu 2 dni, co bardzo mnie zaskoczyło. Opakowanie było solidne i estetyczne. Na pewno zamówię ponownie."),
    array("name" => "Artur F.", "text" => "Wszystko przebiegło bezproblemowo."),
    array("name" => "Mariusz D.", "text" => "Paczka dotarła wcześniej niż przewidywano."),
    array("name" => "Krzysztof J.", "text" => "Paczka dotarła nienaruszona."),
    array("name" => "Bartosz I.", "text" => "Zamówienie było proste, a dostawa jeszcze prostsza. Wszystkie informacje były jasne i aktualne. Świetna obsługa."),
    array("name" => "Adam K.", "text" => "Brak jakichkolwiek zastrzeżeń."),
    array("name" => "Damian A.", "text" => "Śledzenie przesyłki działało bez zarzutu. Paczka dotarła wcześniej i była starannie zapakowana."),
    array("name" => "Mateusz M.", "text" => "Wszystkie informacje o przesyłce otrzymałem od razu."),
    array("name" => "Bartosz R.", "text" => "Opakowanie schludne, paczka dotarła bezpiecznie."),
    array("name" => "Andrzej Z.", "text" => "Dostawa szybsza, niż podano."),
    array("name" => "Tomasz G.", "text" => "Obsługa zawsze dostępna."),
    array("name" => "Wojciech F.", "text" => "Nie miałem żadnych problemów, wszystko przebiegło sprawnie."),
    array("name" => "Adam Z.", "text" => "Obsługa klienta była bardzo pomocna i szybko odpowiedziała. Dostawa dotarła wcześniej. Polecam."),
    array("name" => "Łukasz V.", "text" => "Jestem bardzo zadowolony."),
    array("name" => "Mirosław B.", "text" => "Bardzo szybka dostawa."),
    array("name" => "Jan G.", "text" => "Starannie zapakowane i szybko dostarczone."),
    array("name" => "Mateusz D.", "text" => "Po zamówieniu wszystko potoczyło się bardzo szybko. Paczka wysłana tego samego dnia i dostarczona następnego."),
    array("name" => "Norbert T.", "text" => "Szybka realizacja zamówienia, świetnie."),
    array("name" => "Artur H.", "text" => "Rzadko spotyka się tak profesjonalną obsługę."),
    array("name" => "Przemysław J.", "text" => "Zamówiłem w poniedziałek, a paczka dotarła w środę. Cały proces był prosty i przejrzysty."),
    array("name" => "Krzysztof T.", "text" => "Dostawa była szybsza niż się spodziewałem. Otrzymywałem powiadomienia na każdym etapie."),
    array("name" => "Łukasz F.", "text" => "Paczka dotarła wcześniej."),
    array("name" => "Marcin Z.", "text" => "Cały proces dostawy był bardzo prosty."),
    array("name" => "Adam L.", "text" => "Od razu po zamówieniu otrzymałem potwierdzenie i numer przesyłki. Paczka dotarła na czas i bez uszkodzeń."),
    array("name" => "Michał N.", "text" => "Paczka dotarła w idealnym stanie."),
    array("name" => "Radosław D.", "text" => "Mam same pochwały – od zamówienia po dostawę wszystko było perfekcyjne. Kurier zadzwonił przed przyjazdem."),
    array("name" => "Mateusz R.", "text" => "Śledzenie dostawy działało doskonale."),
    array("name" => "Paweł L.", "text" => "Paczka dotarła szybko i była dobrze zapakowana."),
    array("name" => "Łukasz F.", "text" => "Wszystko bez stresu – zamówienie, potwierdzenie i dostawa. Świetna obsługa."),
    array("name" => "Sebastian O.", "text" => "Wszystko przebiegło sprawnie i szybko."),
    array("name" => "Mariusz E.", "text" => "Doceniam to, że kurier zadzwonił przed przyjazdem. Wszystko było ustalone wcześniej."),
    array("name" => "Rafał K.", "text" => "Kurier był bardzo pomocny."),
    array("name" => "Patryk B.", "text" => "Wszystko przebiegło sprawnie i schludnie."),
    array("name" => "Zbigniew J.", "text" => "Pochwały dla obsługi klienta, szybka pomoc."),
    array("name" => "Dariusz L.", "text" => "Kurier zadzwonił przed dostawą, świetna organizacja."),
    array("name" => "Paweł R.", "text" => "Kurier był uprzejmy i profesjonalny. Paczka dotarła bez problemów."),
    array("name" => "Stanisław H.", "text" => "Kurier był bardzo pomocny."),
    array("name" => "Wiesław D.", "text" => "Dostawa szybka i schludna."),
    array("name" => "Radosław K.", "text" => "Dostawa szybka, paczka bez uszkodzeń."),
    array("name" => "Borys I.", "text" => "Świetna usługa dostawy."),
    array("name" => "Artur V.", "text" => "Paczka dotarła dobrze zapakowana i bez uszkodzeń. Widać dbałość o detale."),
    array("name" => "Stanisław P.", "text" => "Kurier skontaktował się przed dostawą."),
    array("name" => "Adam J.", "text" => "Starannie zapakowane, same pochwały."),
    array("name" => "Damian E.", "text" => "Pochwały za szybkość i punktualność."),
    array("name" => "Tomasz O.", "text" => "Wszystko dokładnie tak, jak opisano."),
    array("name" => "Krzysztof H.", "text" => "Wszystko zgodnie z planem."),
    array("name" => "Bartosz P.", "text" => "Same pochwały."),
    array("name" => "Szymon K.", "text" => "Wszystko świetnie."),
    array("name" => "Przemysław F.", "text" => "Kurier był punktualny i uprzejmy."),
    array("name" => "Łukasz Z.", "text" => "Wszystko było doskonałe."),
    array("name" => "Mariusz J.", "text" => "Nie musiałem długo czekać."),
    array("name" => "Sławomir J.", "text" => "Cały proces zamówienia i dostawy był bardzo przyjemny."),
    array("name" => "Mateusz C.", "text" => "Dostawa super."),
    array("name" => "Michał E.", "text" => "Dostawa bez zarzutu."),
    array("name" => "Adam M.", "text" => "Wszystko było jasne i przejrzyste."),
    array("name" => "Łukasz B.", "text" => "Wszystkie informacje były dostępne."),
    array("name" => "Jan D.", "text" => "Informacje o dostawie były bardzo czytelne."),
    array("name" => "Norbert B.", "text" => "Solidne i bezpieczne opakowanie."),
    array("name" => "Michał R.", "text" => "Dotarło bardzo szybko."),
    array("name" => "Kamil D.", "text" => "Kurier był bardzo uprzejmy."),
    array("name" => "Leon M.", "text" => "Wszystko dotarło na czas i w porządku."),
    array("name" => "Sebastian M.", "text" => "Paczka dotarła na czas."),
    array("name" => "Michał V.", "text" => "Solidne opakowanie, paczka bez uszkodzeń."),
    array("name" => "Karol N.", "text" => "Same pochwały za obsługę."),
    array("name" => "Łukasz K.", "text" => "Kurier był bardzo profesjonalny."),
    array("name" => "Adam T.", "text" => "Opakowanie bardzo solidne."),
    array("name" => "Artur G.", "text" => "Solidne opakowanie."),
    array("name" => "Marcin G.", "text" => "Świetna komunikacja z obsługą."),
    array("name" => "Dariusz O.", "text" => "Dostawa była wyjątkowo szybka."),
    array("name" => "Robert E.", "text" => "Opakowanie estetyczne i solidne."),
    array("name" => "Filip M.", "text" => "Wszystko prosto i bez komplikacji."),
    array("name" => "Artur I.", "text" => "Po zamówieniu od razu dostałem dane do śledzenia. Dostawa punktualna i schludna."),
    array("name" => "Marcin P.", "text" => "Szybka dostawa, wszystko starannie zapakowane."),
    array("name" => "Jerzy K.", "text" => "Proces dostawy był bardzo przejrzysty. Otrzymywałem powiadomienia na każdym etapie."),
    array("name" => "Szczepan G.", "text" => "Świetna obsługa, kurier bardzo profesjonalny."),
    array("name" => "Bruno Z.", "text" => "Wszystko dotarło dokładnie na czas."),
    array("name" => "Sławomir P.", "text" => "Dostawa przebiegła bezproblemowo. Kurier uprzejmy, paczka schludna."),
    array("name" => "Łukasz J.", "text" => "Szybka dostawa, miły kurier i paczka w idealnym stanie."),
    array("name" => "Michał S.", "text" => "Kurier był bardzo uprzejmy."),
    array("name" => "Artur K.", "text" => "Każdy etap dostawy był jasno komunikowany. Paczka dotarła wcześniej."),
    array("name" => "Kamil N.", "text" => "Obsługa dostępna nawet w weekendy."),
    array("name" => "Filip K.", "text" => "Śledzenie przesyłki działało idealnie."),
    array("name" => "Łukasz C.", "text" => "Wszystko jasno, bez opóźnień."),
    array("name" => "Karol P.", "text" => "Bardzo prosty odbiór."),
    array("name" => "Wiesław C.", "text" => "Szybka i niezawodna dostawa."),
    array("name" => "Paweł V.", "text" => "Wszystko przebiegło bez problemów."),
    array("name" => "Artur I.", "text" => "Dostawa wykonana perfekcyjnie. Kurier uprzejmy i kontaktowy."),
    array("name" => "Karol C.", "text" => "Wszystko dotarło bez opóźnień."),
    array("name" => "Robert N.", "text" => "Obsługa informowała mnie na bieżąco."),
    array("name" => "Sebastian E.", "text" => "Zwykle jestem sceptyczny wobec opinii, ale tutaj wszystko się zgadza."),
    array("name" => "Marek T.", "text" => "Nie miałem żadnych problemów."),
    array("name" => "Mariusz L.", "text" => "Paczka dotarła nienaruszona i schludna."),
    array("name" => "Andrzej P.", "text" => "Wszystko szybko i bezproblemowo. Dostawa na czas. Polecam."),
    array("name" => "Karol N.", "text" => "Same pochwały za obsługę."),
    array("name" => "Michał K.", "text" => "Dostawa bardzo szybka, kurier uprzejmy. Paczka w idealnym stanie."),
    array("name" => "Tomasz H.", "text" => "Bardzo prosty proces zamówienia."),
    array("name" => "Wojciech R.", "text" => "Nie czekałem długo, wszystko dotarło szybko."),
    array("name" => "Radosław L.", "text" => "Wszystko było szybkie i proste. Dostawa bezpieczna."),
    array("name" => "Michał S.", "text" => "Kurier był bardzo uprzejmy.")
);
?>
