<?php
$auto_reviews_en = array(
    array("name" => "Paweł E.", "text" => "Kolor pozostaje intensywny nawet po wielu praniach."),
    array("name" => "Radosław H.", "text" => "Koszulka Noriks naprawdę mnie zaskoczyła. Materiał jest gładki dla skóry, a krój podkreśla sylwetkę bez ucisku. Nawet po całym dniu noszenia pozostaje świeża."),
    array("name" => "Kamil V.", "text" => "Wygląda nowocześnie i luksusowo, mimo przystępnej ceny."),
    array("name" => "Daniel B.", "text" => "Noszę ją codziennie."),
    array("name" => "Mateusz L.", "text" => "Na początku miałem wątpliwości, ale przerosła moje oczekiwania. Na pewno kupię kolejną."),
    array("name" => "Michał I.", "text" => "Minimalistyczny design, pasuje do wszystkiego."),
    array("name" => "Tomasz S.", "text" => "Po kilkunastu praniach wygląda jak nowa."),
    array("name" => "Patryk H.", "text" => "Nie widać potu."),
    array("name" => "Marcin U.", "text" => "Pasuje zarówno na szczupłych, jak i bardziej umięśnionych."),
    array("name" => "Andrzej P.", "text" => "Noriks stał się moim codziennym standardem. Miękka, a jednocześnie solidna, nie traci formy. Rozmiar zgodny z tabelą."),
    array("name" => "Maciej K.", "text" => "Materiał lekki, ale nieprześwitujący."),
    array("name" => "Dariusz Z.", "text" => "Bardzo wygodna koszulka. Zamówiłem już kolejną."),
    array("name" => "Karol I.", "text" => "Pasuje do wszystkich kolorów."),
    array("name" => "Adam L.", "text" => "Wystarczająco długa, żeby pozostać w spodniach."),
    array("name" => "Bartosz H.", "text" => "Materiał nie drapie i nie podrażnia skóry, nawet przy poceniu."),
    array("name" => "Tomasz J.", "text" => "Do sportu i na miasto."),
    array("name" => "Zbigniew G.", "text" => "Miękki, a jednocześnie wytrzymały materiał."),
    array("name" => "Stanisław T.", "text" => "Od pierwszego spojrzenia widać, że to nie jest tania koszulka."),
    array("name" => "Borys C.", "text" => "Prosta, ale wygląda nowocześnie."),
    array("name" => "Daniel P.", "text" => "Dostałem więcej, niż się spodziewałem."),
    array("name" => "Marek U.", "text" => "Zabrałem ją w podróż – nie pognietła się nawet po wielu godzinach w walizce."),
    array("name" => "Adam R.", "text" => "Super lekka i wygodna."),
    array("name" => "Łukasz L.", "text" => "Noszę ją zarówno z marynarką, jak i z dresami."),
    array("name" => "Krzysztof O.", "text" => "Trwały kolor."),
    array("name" => "Marcin E.", "text" => "Mam ich już pięć."),
    array("name" => "Grzegorz T.", "text" => "Świetne połączenie wyglądu i funkcjonalności."),
    array("name" => "Mariusz M.", "text" => "Premium czuć już przy pierwszym dotyku."),
    array("name" => "Robert L.", "text" => "Wygląda męsko i elegancko."),
    array("name" => "Artur J.", "text" => "Noszę ją niemal co drugi dzień – nie wychodzi z rotacji."),
    array("name" => "Krzysztof T.", "text" => "Miękka jak bawełna, ale bardziej wytrzymała."),
    array("name" => "Alan M.", "text" => "Materiał miękki, ale nie rozciąga się nawet po kilku praniach."),
    array("name" => "Filip P.", "text" => "Noriks przekonał mnie już przy pierwszym założeniu. Oddychająca i nie przylega do skóry."),
    array("name" => "Bruno L.", "text" => "Idealna długość rękawów."),
    array("name" => "Gordon F.", "text" => "Długo szukałem takiego modelu. Dzięki!"),
    array("name" => "Mateusz B.", "text" => "Bardzo odporna na zużycie – wygląda jak nowa."),
    array("name" => "Łukasz T.", "text" => "Luksusowa w dotyku."),
    array("name" => "Piotr N.", "text" => "Świetnie wygląda z kurtką."),
    array("name" => "Paweł V.", "text" => "Po kilku praniach brak śladów zużycia czy blaknięcia. Na pewno kupię kolejną."),
    array("name" => "Igor N.", "text" => "Nie gniecie się nawet po całym dniu."),
    array("name" => "Norbert U.", "text" => "Kolor na żywo wygląda jeszcze lepiej – głęboki i nowoczesny."),
    array("name" => "Szymon Z.", "text" => "Materiał łatwy w prasowaniu."),
    array("name" => "Jerzy Z.", "text" => "Jestem zachwycony! Dokładnie tego szukałem."),
    array("name" => "Adrian L.", "text" => "Pasuje do każdych spodni."),
    array("name" => "Artur F.", "text" => "Dobrze leży nawet jeśli jestem między rozmiarami."),
    array("name" => "Adam K.", "text" => "Idealny rozmiar."),
    array("name" => "Sebastian G.", "text" => "Idealna koszulka dla nowoczesnego mężczyzny."),
    array("name" => "Dawid M.", "text" => "Klasyka z nutą stylu."),
    array("name" => "Tomasz A.", "text" => "Sportowy charakter z eleganckim wykończeniem."),
    array("name" => "Mariusz H.", "text" => "Do biura i na wolny czas."),
    array("name" => "Łukasz I.", "text" => "Brak ucisku pod pachami."),
    array("name" => "Adam M.", "text" => "Idealny krój mimo mojego wzrostu."),
    array("name" => "Stefan K.", "text" => "Znalazłem nową ulubioną."),
    array("name" => "Bartosz S.", "text" => "Idealna na podróże – lekka i kompaktowa."),
    array("name" => "Franciszek C.", "text" => "Założyłem ją na rozmowę kwalifikacyjną – czułem się pewnie."),
    array("name" => "Tomasz H.", "text" => "Idealna długość i krój."),
    array("name" => "Krzysztof G.", "text" => "Noszę ją do pracy i na miasto."),
    array("name" => "Władysław G.", "text" => "Elegancka i wygodna."),
    array("name" => "Jan L.", "text" => "Idealna równowaga między elegancją a wygodą."),
    array("name" => "Łukasz T.", "text" => "Świetna na trening i na co dzień."),
    array("name" => "Adam J.", "text" => "Jakość przewyższa cenę."),
    array("name" => "Leon Z.", "text" => "Zachowuje kształt i kolor."),
    array("name" => "Bartosz E.", "text" => "Łatwo wystylizować na bardziej elegancki look."),
    array("name" => "Marcin T.", "text" => "Dostałem mnóstwo komplementów."),
    array("name" => "Mateusz H.", "text" => "Nie zbiera kłaczków."),
    array("name" => "Tadeusz V.", "text" => "Dobrze trzyma się przez cały dzień."),
    array("name" => "Filip Z.", "text" => "Koszulka na każdą okazję."),
    array("name" => "Dariusz V.", "text" => "Wygodna przez cały dzień."),
    array("name" => "Mirosław D.", "text" => "Minimalistyczny, męski design."),
    array("name" => "Sebastian O.", "text" => "Idealna na co dzień."),
    array("name" => "Robert G.", "text" => "Najlepszy zakup online."),
    array("name" => "Artur G.", "text" => "Mój pierwszy wybór każdego ranka."),
    array("name" => "Paweł L.", "text" => "Leży jak szyta na miarę."),
    array("name" => "Mateusz V.", "text" => "Krój Noriks jest perfekcyjnie dopasowany."),
    array("name" => "Alan W.", "text" => "Wygląda drożej niż jest w rzeczywistości."),
    array("name" => "Emil W.", "text" => "Wygląda jak z wyższej półki."),
    array("name" => "Michał U.", "text" => "Materiał miękki i odporny na ślady użytkowania."),
    array("name" => "Tadeusz E.", "text" => "Rękawy nie są zbyt ciasne."),
    array("name" => "Piotr M.", "text" => "Dawno nie byłem tak zadowolony z podstawowej koszulki."),
    array("name" => "Dominik T.", "text" => "Na spacery i wyjścia."),
    array("name" => "Bruno K.", "text" => "Nie deformuje się."),
    array("name" => "Artur I.", "text" => "Najwygodniejsza koszulka tego sezonu."),
    array("name" => "Marek P.", "text" => "Nie mogę się doczekać aż wyschnie po praniu."),
    array("name" => "Karol U.", "text" => "Styl casual, który lubię."),
    array("name" => "Patryk Z.", "text" => "Świetny stosunek ceny do jakości."),
    array("name" => "Fabian R.", "text" => "Nie gniecie się łatwo – idealna dla mnie."),
    array("name" => "Zbigniew F.", "text" => "Nowoczesna bez utraty komfortu."),
    array("name" => "Marcin P.", "text" => "Noriks wygląda schludnie przez cały dzień."),
    array("name" => "Jan X.", "text" => "Lekka na lato, idealna warstwowo jesienią."),
    array("name" => "Władimir K.", "text" => "Stała się moją ulubioną."),
    array("name" => "Erik J.", "text" => "Na żywo wygląda jeszcze lepiej niż na zdjęciach."),
    array("name" => "Tomasz S.", "text" => "Wyjątkowy wygląd i komfort."),
    array("name" => "Karol Z.", "text" => "Świetna również pod sweter."),
    array("name" => "Zbigniew N.", "text" => "Nie zsuwa się z ramion."),
    array("name" => "Adam D.", "text" => "Wygodna i profesjonalna."),
    array("name" => "Natan G.", "text" => "Pozostaje świeża nawet po całym dniu."),
    array("name" => "Karol M.", "text" => "Idealna także dla wyższych osób."),
    array("name" => "Borys T.", "text" => "Tak wygodna, jak piżama."),
    array("name" => "Filip K.", "text" => "Idealna długość – nie podwija się."),
    array("name" => "Tomasz J.", "text" => "Szybko schnie – idealna w podróży."),
    array("name" => "Stanisław M.", "text" => "Wygląda świetnie i jest niesamowicie wygodna."),
    array("name" => "Grzegorz V.", "text" => "Jeśli szukasz czegoś solidnego – to jest to."),
    array("name" => "Dawid I.", "text" => "Praktyczna i nowoczesna."),
    array("name" => "Sebastian B.", "text" => "Każdy outfit wygląda lepiej."),
    array("name" => "Norbert D.", "text" => "Dziewczyna dała 5/5 – to mówi wszystko."),
    array("name" => "Wojciech G.", "text" => "Po każdym praniu wygląda jak nowa."),
    array("name" => "Adam Z.", "text" => "Stała się częścią mojego codziennego stylu."),
    array("name" => "Mateusz D.", "text" => "Idealny balans sportowego i eleganckiego stylu."),
    array("name" => "Marek R.", "text" => "Noriks jest w mojej rotacji co tydzień."),
    array("name" => "Mateusz V.", "text" => "Cieszę się, że krój nie zwisa w talii."),
    array("name" => "Filip F.", "text" => "Nie zmienia kształtu po praniu."),
    array("name" => "Alan C.", "text" => "Kolor zachował intensywność po wielu praniach."),
    array("name" => "Mateusz P.", "text" => "Dopasowany, ale wygodny krój."),
    array("name" => "Bartosz K.", "text" => "Świetna nawet dla mocniejszej sylwetki."),
    array("name" => "Tomasz G.", "text" => "Wytrzymała nawet po sporcie."),
    array("name" => "Andrzej N.", "text" => "Świetnie oddycha nawet w ciężkie dni."),
    array("name" => "Artur K.", "text" => "Materiał wygląda jakościowo i łatwo się komponuje."),
    array("name" => "Sebastian R.", "text" => "Przeszła test 12 godzin pracy."),
    array("name" => "Adam N.", "text" => "Szukałem takiej koszulki od lat."),
    array("name" => "Dominik R.", "text" => "Pasuje do wszystkiego."),
    array("name" => "Łukasz W.", "text" => "Świetna alternatywa dla koszuli."),
    array("name" => "Emil T.", "text" => "Idealna na co dzień – nie zastanawiam się co założyć."),
    array("name" => "Robert N.", "text" => "Po miesiącu prania wygląda jak pierwszego dnia."),
    array("name" => "Marcin Q.", "text" => "Brak dyskomfortu nawet po całym dniu."),
    array("name" => "Mateusz J.", "text" => "Idealna zarówno do pracy, jak i casual."),
    array("name" => "Jan E.", "text" => "Leży jak ulał."),
    array("name" => "Sebastian F.", "text" => "Wygląda jak nowa nawet po wielu użyciach."),
    array("name" => "Dariusz W.", "text" => "Wygodna w każdej pozycji."),
    array("name" => "Łukasz B.", "text" => "Noszę ją codziennie."),
    array("name" => "Krystian D.", "text" => "Wygląda jak szyta na miarę."),
    array("name" => "Michał G.", "text" => "Świetnie radzi sobie z potem."),
    array("name" => "Bartosz V.", "text" => "Nie rozciąga się po praniu."),
    array("name" => "Damian S.", "text" => "Idealna do stylizacji warstwowych."),
    array("name" => "Artur V.", "text" => "Świeżość utrzymuje się cały dzień."),
    array("name" => "Tomasz L.", "text" => "Komfortowa nawet na słońcu."),
    array("name" => "Krzysztof L.", "text" => "Dostałem mnóstwo komplementów."),
    array("name" => "Borys M.", "text" => "Rzadko piszę recenzje, ale tu musiałem."),
    array("name" => "Radosław K.", "text" => "Łatwa w praniu i szybkoschnąca."),
    array("name" => "Grzegorz S.", "text" => "Detale przy kołnierzu są świetnie wykonane."),
    array("name" => "Adam Z.", "text" => "Element codziennego stylu."),
    array("name" => "Bruno G.", "text" => "Wygląda na trwałą przez lata."),
    array("name" => "Michał C.", "text" => "Krój maskuje drobne niedoskonałości."),
    array("name" => "Filip O.", "text" => "Obsługa bardzo dobra."),
    array("name" => "Zbigniew D.", "text" => "Kupiłem jedną i od razu zamówiłem trzy kolejne."),
    array("name" => "Łukasz P.", "text" => "Wygodna nawet po całym dniu."),
    array("name" => "Stanisław P.", "text" => "Wystarczająco elastyczna."),
    array("name" => "Marek S.", "text" => "Wygląda schludnie nawet po praniu."),
    array("name" => "Wiktor I.", "text" => "Nie klei się do ciała."),
    array("name" => "Artur R.", "text" => "Prosta i perfekcyjna."),
    array("name" => "Karol R.", "text" => "Najwygodniejsza koszulka jaką mam."),
    array("name" => "Krzysztof A.", "text" => "Idealna również na zimę pod bluzę."),
    array("name" => "Tomasz E.", "text" => "Polecona i faktycznie świetna."),
    array("name" => "Andrzej J.", "text" => "Dobra inwestycja – styl i funkcjonalność."),
    array("name" => "Paweł H.", "text" => "Różnica w kroju robi ogromne wrażenie."),
    array("name" => "Bartosz P.", "text" => "Same pochwały."),
    array("name" => "Mirosław Z.", "text" => "Od razu wygląda się schludniej."),
    array("name" => "Filip B.", "text" => "Nigdy nie miałem tak wygodnej koszulki."),
    array("name" => "Mateusz E.", "text" => "Materiał gładki i przyjazny dla skóry."),
    array("name" => "Marcin D.", "text" => "Nie zbiera kurzu ani włosków."),
    array("name" => "Adam D.", "text" => "Idealna dla osób ceniących komfort i styl."),
    array("name" => "Krzysztof N.", "text" => "Noszona cały dzień na słońcu – zero dyskomfortu."),
    array("name" => "Mariusz K.", "text" => "Nowoczesny krój bez przesady."),
    array("name" => "Sebastian E.", "text" => "Zwykle jestem sceptyczny, ale tu wszystko się zgadza."),
    array("name" => "Michał H.", "text" => "Czysty wygląd i maksymalna wygoda."),
    array("name" => "Damian V.", "text" => "Do pracy i na wieczorne wyjścia."),
    array("name" => "Bożydar J.", "text" => "Świetna odmiana bez zbędnych nadruków."),
    array("name" => "Daniel K.", "text" => "Połączenie wygody i elegancji."),
    array("name" => "Jakub P.", "text" => "Od razu zamówiłem kolejne dwie."),
    array("name" => "Leon F.", "text" => "Delikatny połysk wygląda bardzo elegancko."),
    array("name" => "Grzegorz J.", "text" => "Uwielbiam dopasowany krój."),
    array("name" => "Michał R.", "text" => "Dawno nie byłem tak zadowolony z zakupu online."),
    array("name" => "Tadeusz B.", "text" => "Idealna na co dzień – prosta i solidna."),
    array("name" => "Marek K.", "text" => "Świetne odczucie na skórze, zero podrażnień."),
    array("name" => "Andrzej V.", "text" => "Stabilna jakość tydzień po tygodniu."),
    array("name" => "Paweł C.", "text" => "Warta każdej złotówki."),
    array("name" => "Tomasz N.", "text" => "Przetrwała pralkę i suszarkę."),
    array("name" => "Borys U.", "text" => "Mam ją w kilku kolorach."),
    array("name" => "Alan T.", "text" => "Pierwsze wrażenie? Wow."),
    array("name" => "Stanisław H.", "text" => "Kołnierz nie deformuje się po praniu."),
    array("name" => "Dawid E.", "text" => "Najlepsza koszulka, jaką kupiłem."),
    array("name" => "Artur H.", "text" => "Dokładnie to, czego szukałem."),
    array("name" => "Filip L.", "text" => "Jakość wykonania na bardzo wysokim poziomie."),
    array("name" => "Mateusz T.", "text" => "Lekka, ale bardzo trwała."),
    array("name" => "Radosław O.", "text" => "Niesamowite uczucie swobody."),
    array("name" => "Piotr B.", "text" => "Świetna także przy wilgotnej pogodzie."),
    array("name" => "Franciszek D.", "text" => "Kupiłem kilka sztuk."),
    array("name" => "Krzysztof M.", "text" => "Elastyczna i bardzo wygodna."),
    array("name" => "Adam R.", "text" => "Idealna na lato i zimę."),
    array("name" => "Mariusz F.", "text" => "Wygląda profesjonalnie."),
    array("name" => "Sebastian C.", "text" => "Wytrzymuje intensywne użytkowanie."),
    array("name" => "Władysław F.", "text" => "Nie traci formy po wielu praniach."),
    array("name" => "Artur J.", "text" => "Lepsza niż droższe marki."),
    array("name" => "Łukasz V.", "text" => "Trzyma formę nawet po całym dniu."),
    array("name" => "Patryk V.", "text" => "Po miesiącach wygląda jak nowa."),
    array("name" => "Mateusz N.", "text" => "Idealna gęstość materiału."),
    array("name" => "Bogdan C.", "text" => "Pierwsza, która leżała idealnie."),
    array("name" => "Jerzy U.", "text" => "Idealnie dopasowana do mojej sylwetki."),
    array("name" => "Marek S.", "text" => "Kurier był bardzo uprzejmy."),
    array("name" => "Grzegorz J.", "text" => "Minimalizm, który naprawdę działa."),
    array("name" => "Krzysztof Y.", "text" => "Za każdym razem czuję się pewnie."),
    array("name" => "Wojciech F.", "text" => "Idealna koszulka na co dzień."),
    array("name" => "Dariusz O.", "text" => "Lekka, ale trzyma linię."),
    array("name" => "Krzysztof H.", "text" => "Kołnierz pozostaje idealny."),
    array("name" => "Tadeusz G.", "text" => "Od razu wiedziałem, że kupię ponownie."),
    array("name" => "Angelo M.", "text" => "Tekstura jest rewelacyjna."),
    array("name" => "Zbigniew T.", "text" => "Bardzo szybka dostawa."),
    array("name" => "Krzysztof J.", "text" => "Idealnie leży w ramionach."),
    array("name" => "Andrzej P.", "text" => "Najlepszy stosunek ceny do jakości."),
    array("name" => "Alan J.", "text" => "Jakby była szyta na miarę."),
    array("name" => "Franciszek E.", "text" => "Kolor na żywo jeszcze lepszy."),
    array("name" => "Karol V.", "text" => "Miękka i solidna jednocześnie."),
    array("name" => "Marcin K.", "text" => "Miękka i odporna."),
    array("name" => "Filip T.", "text" => "Brak drażniących szwów."),
    array("name" => "Szymon R.", "text" => "Po jednej zamówiłem kolejne trzy."),
    array("name" => "Igor T.", "text" => "Świetny krój – podkreśla ramiona."),
    array("name" => "Daniel E.", "text" => "Rzadko spotykam tak dobre dopasowanie."),
    array("name" => "Artur I.", "text" => "Idealna zarówno na siłownię, jak i do biura."),
    array("name" => "Sebastian O.", "text" => "Wygląda schludnie nawet po wielu godzinach."),
    array("name" => "Alan V.", "text" => "Czarna wersja wygląda fenomenalnie."),
    array("name" => "Patryk B.", "text" => "Świetna równowaga między casual a smart."),
    array("name" => "Rafał C.", "text" => "Nie mechaci się nawet po wielu praniach."),
    array("name" => "Mariusz D.", "text" => "Od razu stała się moim faworytem."),
    array("name" => "Tomasz R.", "text" => "Szybko schnie i nie wymaga prasowania."),
    array("name" => "Zbigniew T.", "text" => "Cenię prostotę – ta koszulka to ma."),
    array("name" => "Borys T.", "text" => "Tak wygodna, że aż zapominam, że ją mam."),
    array("name" => "Sebastian M.", "text" => "Pewny wybór na każdy dzień."),
    array("name" => "Dariusz B.", "text" => "Lekka, nieprześwitująca, wygodna."),
    array("name" => "Adam T.", "text" => "Rozmiar L leży idealnie."),
    array("name" => "Andrzej P.", "text" => "Świetny krój i komfort."),
    array("name" => "Piotr V.", "text" => "Najlepsza koszulka w tej cenie."),
    array("name" => "Wiesław D.", "text" => "Wygląda dobrze przez cały dzień."),
    array("name" => "Norbert T.", "text" => "Idealna nawet w upale."),
    array("name" => "Sebastian B.", "text" => "Podnosi każdy outfit."),
    array("name" => "Artur V.", "text" => "Pozostaje świeża przez cały dzień."),
    array("name" => "Wiesław K.", "text" => "Wygląd i komfort przewyższają cenę."),
    array("name" => "Dariusz L.", "text" => "Brak podrażnień nawet po całym dniu."),
    array("name" => "Renat K.", "text" => "Czysty, nowoczesny krój."),
    array("name" => "Tomasz A.", "text" => "Nie traci kształtu."),
    array("name" => "Marek G.", "text" => "Świetna do każdej stylizacji."),
    array("name" => "Łukasz C.", "text" => "Biała wersja nie prześwituje."),
    array("name" => "Mateusz O.", "text" => "Równe krawędzie, zero fal."),
    array("name" => "Stanisław Z.", "text" => "Rozmiar XXL leży lepiej niż u konkurencji."),
    array("name" => "Sebastian T.", "text" => "Oddychający materiał nawet w upały."),
    array("name" => "Artur M.", "text" => "Idealna na co dzień."),
    array("name" => "Paweł N.", "text" => "Widać dbałość o detale."),
    array("name" => "Jakub R.", "text" => "Nie kurczy się po suszeniu."),
    array("name" => "Krystian W.", "text" => "Lekko taliowana, ale bez ucisku."),
    array("name" => "Tomasz F.", "text" => "Jakość klasy premium."),
    array("name" => "Wojciech R.", "text" => "Wygląda drogo, a jest przystępna."),
    array("name" => "Mariusz J.", "text" => "Idealnie wyważona grubość materiału."),
    array("name" => "Adam B.", "text" => "Jedna koszulka do wszystkiego."),
    array("name" => "Robert E.", "text" => "Perfekcyjne szwy i wykończenie."),
    array("name" => "Michał P.", "text" => "Świeży wygląd nawet po wielu noszeniach."),
    array("name" => "Mateusz Y.", "text" => "Ciemnozielona wygląda świetnie."),
    array("name" => "Sebastian H.", "text" => "Rozmiar M idealny – rękawy krótsze, jak lubię."),
    array("name" => "Filip M.", "text" => "Proces zamówienia bezproblemowy."),
    array("name" => "Tomasz S.", "text" => "Wygląda jak marka premium."),
    array("name" => "Alan J.", "text" => "Jak szyta na miarę."),
    array("name" => "Włodzimierz C.", "text" => "Szybka dostawa, świetnie zapakowana."),
    array("name" => "Dawid I.", "text" => "Idealna na luźny poranek i elegancką kolację."),
    array("name" => "Karol M.", "text" => "Mam wrażliwą skórę – zero podrażnień."),
    array("name" => "Franciszek P.", "text" => "Brak nieprzyjemnego zapachu po całym dniu."),
    array("name" => "Zoran L.", "text" => "Maskuje brzuch i poszerza ramiona."),
    array("name" => "Dariusz I.", "text" => "Jedna koszulka – wiele zastosowań."),
    array("name" => "Igor S.", "text" => "Proces zamówienia bardzo prosty."),
    array("name" => "Artur D.", "text" => "Biała i granatowa – idealny duet."),
    array("name" => "Andrzej K.", "text" => "Czuję się w niej pewniej."),
    array("name" => "Marek N.", "text" => "Po wysuszeniu idealnie gładka."),
    array("name" => "Grzegorz P.", "text" => "Miękkie szwy, zero otarć."),
    array("name" => "Sebastian D.", "text" => "Mój wybór do biura."),
    array("name" => "Adam G.", "text" => "Materiał nie mechaci się."),
    array("name" => "Leon C.", "text" => "Kolor zgodny ze zdjęciem."),
    array("name" => "Damian P.", "text" => "Wygląda jak dużo droższy produkt."),
    array("name" => "Erwin S.", "text" => "Świetne pierwsze wrażenie."),
    array("name" => "Szczepan G.", "text" => "Obsługa i dostawa na najwyższym poziomie."),
    array("name" => "Michał M.", "text" => "Wytrzymała nawet intensywne noszenie."),
    array("name" => "Krzysztof V.", "text" => "Brak plam nawet po całym dniu."),
    array("name" => "Stanisław O.", "text" => "Rozmiar XL idealny."),
    array("name" => "Bartosz R.", "text" => "Idealna dla fanów czystych linii."),
    array("name" => "Artur Ś.", "text" => "Od siłowni po kawiarnię."),
    array("name" => "Marek P.", "text" => "Szary kolor wygląda bardzo elegancko."),
    array("name" => "Filip G.", "text" => "Wygodna nawet w podróży."),
    array("name" => "Adam Y.", "text" => "Polecam każdemu."),
    array("name" => "Karol P.", "text" => "Trzyma formę nawet pod koszulą."),
    array("name" => "Mateusz D.", "text" => "Dla tych, którzy chcą wyglądać dobrze bez wysiłku."),
    array("name" => "Emil C.", "text" => "Po prostu idealna. Mam wszystkie kolory.")
);
?>
