<?php
$auto_reviews_en = array(
    array("name" => "Paweł M.", "text" => "Kolor bokserek pozostaje taki sam nawet po wielu praniach, nic nie blaknie."),
    array("name" => "Michał P.", "text" => "Bokserki Noriks naprawdę mnie zaskoczyły. Materiał jest miękki, nie drapie i nie uciska tam, gdzie nie powinien."),
    array("name" => "Marcin S.", "text" => "Naprawdę wygodne bokserki na cały dzień, praktycznie ich nie czuję."),
    array("name" => "Tomasz R.", "text" => "Guma w pasie jest solidna, ale nie uciska i nie wrzyna się w skórę."),
    array("name" => "Jan D.", "text" => "Przewiewne i lekkie, idealne do pracy i na siłownię."),
    array("name" => "Łukasz M.", "text" => "Bokserki zachowują kształt nawet po wielu praniach, nic się nie rozciąga."),
    array("name" => "Krzysztof C.", "text" => "Materiał jest gładki dla skóry, brak drażniących szwów."),
    array("name" => "Dariusz V.", "text" => "Po całym dniu wszystko pozostaje na swoim miejscu, nic się nie podwija."),
    array("name" => "Marek L.", "text" => "Bokserki Noriks sprawiają wrażenie jakościowych już przy pierwszym dotyku."),
    array("name" => "Piotr G.", "text" => "Noszę je od tygodni – brak mechacenia i rozciągania."),
    array("name" => "Artur B.", "text" => "Idealny krój, dopasowane do ciała, ale bez ucisku."),
    array("name" => "Filip J.", "text" => "Nogawki nie podciągają się do góry – ogromny plus."),
    array("name" => "Krzysztof R.", "text" => "Noriks to moja pierwsza opcja w szufladzie, zawsze po nie sięgam."),
    array("name" => "Maciej S.", "text" => "Brak nieprzyjemnego pocenia, materiał dobrze oddycha."),
    array("name" => "Dominik K.", "text" => "Wyglądają na bardzo trwałe, szwy są równe i solidne."),
    array("name" => "Adam H.", "text" => "Świetny stosunek ceny do jakości, lepsze niż wiele droższych marek."),
    array("name" => "Zbigniew P.", "text" => "Nie podwijają się pod spodniami, wszystko pozostaje równo."),
    array("name" => "Bartosz N.", "text" => "Świetnie leżą, mimo że jestem między rozmiarami."),
    array("name" => "Rafał T.", "text" => "Guma nie traci elastyczności nawet po wielu praniach."),
    array("name" => "Andrzej M.", "text" => "Idealne do pracy i na trening – nie zmieniam już marki."),
    array("name" => "Dawid K.", "text" => "Czuję się jak w piżamie, a wyglądają schludnie i nowocześnie."),
    array("name" => "Leon B.", "text" => "Dobrze modelują sylwetkę, bez workowatego efektu."),
    array("name" => "Tomasz Z.", "text" => "Materiał szybko schnie, idealne w podróży."),
    array("name" => "Wiesław H.", "text" => "Nie powodują dyskomfortu nawet przy długim siedzeniu."),
    array("name" => "Krzysztof F.", "text" => "Brak drażniących metek, wszystko świetnie wykończone."),
    array("name" => "Tadeusz K.", "text" => "Noszę je cały dzień i nadal czuję komfort."),
    array("name" => "Borys V.", "text" => "Nie skręcają się i nie zawijają pod jeansami."),
    array("name" => "Mariusz C.", "text" => "Krój ładnie układa się na nogach, bez marszczeń."),
    array("name" => "Stanisław C.", "text" => "Kupiłem jedną parę i od razu domówiłem trzy kolejne."),
    array("name" => "Henryk N.", "text" => "Kolor pozostaje intensywny nawet po wielu praniach."),
    array("name" => "Daniel L.", "text" => "Brak nieprzyjemnego zapachu nawet po ciężkim dniu."),
    array("name" => "Grzegorz B.", "text" => "Zastąpiły wszystkie moje stare bokserki."),
    array("name" => "Sebastian R.", "text" => "Nic nie uciska, a jednocześnie daje dobre podparcie."),
    array("name" => "Wojciech M.", "text" => "Idealne na lato, nie kleją się do skóry."),
    array("name" => "Michał J.", "text" => "Gładkie szwy, brak obtarć nawet przy długim chodzeniu."),
    array("name" => "Władysław N.", "text" => "Materiał wystarczająco gruby, ale nadal lekki."),
    array("name" => "Natan E.", "text" => "Świetnie trzymają wszystko na miejscu nawet podczas treningu."),
    array("name" => "Sebastian K.", "text" => "W końcu bielizna, która nie denerwuje."),
    array("name" => "Igor B.", "text" => "Nie skurczyły się ani nie zdeformowały po suszarce."),
    array("name" => "Jan T.", "text" => "Idealne także dla wysokich osób."),
    array("name" => "Tomasz G.", "text" => "Świetne dopasowanie w pasie i na udach."),
    array("name" => "Borys R.", "text" => "Tak wygodne, że prawie ich nie czuję."),
    array("name" => "Karol D.", "text" => "Noszę je do pracy i na siłownię – sprawdzają się wszędzie."),
    array("name" => "Marek H.", "text" => "Guma nie zostawia śladów na skórze."),
    array("name" => "Zbigniew P.", "text" => "Miękkie w dotyku, bez syntetycznego uczucia."),
    array("name" => "Dariusz K.", "text" => "Pierwsze bokserki, które nie podciągają nogawek."),
    array("name" => "Franciszek M.", "text" => "Idealny balans – ani za ciasne, ani za luźne."),
    array("name" => "Patryk H.", "text" => "Zakładam rano i nie muszę poprawiać przez cały dzień."),
    array("name" => "Zbigniew V.", "text" => "Świetne na długie podróże, zero obtarć."),
    array("name" => "Marcin J.", "text" => "Nie tracą formy nawet po miesiącu użytkowania."),
    array("name" => "Tomasz P.", "text" => "Dobrze leżą nawet pod garniturem."),
    array("name" => "Andrzej K.", "text" => "Po nich inne bokserki wypadają słabo."),
    array("name" => "Karol B.", "text" => "Miękkie, ale bardzo wytrzymałe."),
    array("name" => "Michał Z.", "text" => "Brak podrażnień nawet w upały."),
    array("name" => "Łukasz L.", "text" => "Najwygodniejsze bokserki jakie miałem."),
    array("name" => "Wiktor P.", "text" => "Idealna długość, nic nie uciska w kroku."),
    array("name" => "Paweł G.", "text" => "Wrażenie jak w marce premium, a cena normalna."),
    array("name" => "Alan S.", "text" => "Szwy tak dobre, że prawie ich nie czuć."),
    array("name" => "Krystian J.", "text" => "Pozostają gładkie, nie zbierają włosków."),
    array("name" => "Łukasz F.", "text" => "Idealne bokserki na co dzień."),
    array("name" => "Mariusz R.", "text" => "Nawet po intensywnym treningu wszystko na miejscu."),
    array("name" => "Artur C.", "text" => "Bardzo pozytywne zaskoczenie – komfort 10/10."),
    array("name" => "Adam O.", "text" => "Kupiłem kilka par i noszę tylko je."),
    array("name" => "Stefan V.", "text" => "Nie zwijają się nawet pod obcisłymi spodniami."),
    array("name" => "Dawid L.", "text" => "Materiał nie zatrzymuje wilgoci, szybko schnie."),
    array("name" => "Grzegorz U.", "text" => "Idealne dla osób pracujących przy komputerze."),
    array("name" => "Mirosław E.", "text" => "Wyglądają jak nowe nawet po kilku tygodniach."),
    array("name" => "Bruno C.", "text" => "Proste, męskie, bez zbędnych wzorów."),
    array("name" => "Krzysztof K.", "text" => "Idealny balans między wygodą a podparciem."),
    array("name" => "Michał J.", "text" => "Nie uciskają ani w pasie, ani na udach."),
    array("name" => "Szymon P.", "text" => "Łatwe w praniu i szybko schną."),
    array("name" => "Leon M.", "text" => "Kolory dokładnie jak na zdjęciach."),
    array("name" => "Damian D.", "text" => "Wygodne nawet po wielu godzinach w upale."),
    array("name" => "Dorian S.", "text" => "Nie prześwitują pod cienkimi spodniami."),
    array("name" => "Adrian K.", "text" => "Szeroka i stabilna guma, nie zwija się."),
    array("name" => "Rafał H.", "text" => "Czuję się znacznie bardziej komfortowo przez cały dzień."),
    array("name" => "Zbigniew R.", "text" => "Świetne dla mężczyzn o solidnej budowie."),
    array("name" => "Tomasz E.", "text" => "Dają radę i w pracy, i na treningu."),
    array("name" => "Krystian L.", "text" => "W końcu bokserki, których nie trzeba poprawiać."),
    array("name" => "Norbert K.", "text" => "Bardzo zadowolony z zakupu, na pewno kupię kolejne."),
    array("name" => "Dragan V.", "text" => "Nie zsuwają się, trzymają się w pasie cały dzień."),
    array("name" => "Sławomir T.", "text" => "Idealna grubość materiału."),
    array("name" => "Albert N.", "text" => "Świetne na co dzień i w podróży."),
    array("name" => "Zbigniew B.", "text" => "Brak deformacji po praniu."),
    array("name" => "Ilia S.", "text" => "Nie uciskają w pachwinach – duży plus."),
    array("name" => "Mariusz L.", "text" => "Bardzo wygodne nawet przy dużej aktywności."),
    array("name" => "Karol S.", "text" => "Nie wrzynają się w biodra."),
    array("name" => "Sebastian K.", "text" => "Rzadko piszę opinie, ale te bokserki zasługują."),
    array("name" => "Artur Ż.", "text" => "Podnoszą komfort noszenia na zupełnie nowy poziom."),
    array("name" => "Władysław R.", "text" => "Po nich inne bokserki już nie pasują."),
    array("name" => "Grzegorz C.", "text" => "Szybka dostawa i świetny produkt."),
    array("name" => "Wiktor S.", "text" => "Idealnie przylegają, bez podciągania nogawek."),
    array("name" => "Olgierd T.", "text" => "Tak miękkie, że prawie ich nie czuję."),
    array("name" => "Stanisław I.", "text" => "Noszę cały dzień bez żadnego dyskomfortu."),
    array("name" => "Karol H.", "text" => "Świetna guma – nie uciska i nie zwija się."),
    array("name" => "Dawid P.", "text" => "Po praniu bez zmian, bez rozciągania."),
    array("name" => "Adrian V.", "text" => "Świetny, oddychający materiał."),
    array("name" => "Leon M.", "text" => "Idealna długość, nic się nie przesuwa."),
    array("name" => "Augustyn J.", "text" => "Stały się moim numerem jeden."),
    array("name" => "Mateusz U.", "text" => "Brak pocenia nawet po treningu."),
    array("name" => "Dariusz T.", "text" => "Spodziewałem się dobrych, ale te są rewelacyjne."),
    array("name" => "Jerzy A.", "text" => "Miękkie, a jednocześnie solidne."),
    array("name" => "Tomasz S.", "text" => "Nie podciągają się pod spodniami."),
    array("name" => "Benedykt K.", "text" => "W końcu bokserki bez ucisku."),
    array("name" => "Laurent P.", "text" => "Bardzo wysokiej jakości materiał."),
    array("name" => "Ignacy R.", "text" => "Same pochwały, kupię ponownie."),
    array("name" => "Marcin D.", "text" => "Bardzo przyjemne dla skóry."),
    array("name" => "Miron B.", "text" => "Szwy wykonane perfekcyjnie."),
    array("name" => "Renat M.", "text" => "Noszę je w biurze i na treningu – świetne."),
    array("name" => "Teodor Z.", "text" => "Jedyne bokserki, które naprawdę chcę nosić."),
    array("name" => "Bartosz Ś.", "text" => "Mocna guma, ale bez ucisku."),
    array("name" => "Walenty R.", "text" => "Nie zatrzymują wilgoci."),
    array("name" => "Patryk L.", "text" => "Wygodne nawet po wielu godzinach."),
    array("name" => "Tomasz U.", "text" => "Zero podrażnień, nawet w upale."),
    array("name" => "Mariusz Ś.", "text" => "Bardzo solidnie wykonane."),
    array("name" => "Krzysztof D.", "text" => "Nie przesuwają się podczas ćwiczeń."),
    array("name" => "Wiktor P.", "text" => "Po 10 praniach jak nowe."),
    array("name" => "Jerzy T.", "text" => "Bokserki, które w końcu mają sens."),
    array("name" => "Karol K.", "text" => "Materiał nie drapie i nie swędzi."),
    array("name" => "Ernest B.", "text" => "Świetne na co dzień."),
    array("name" => "Roman V.", "text" => "Idealne dla mojej sylwetki."),
    array("name" => "Marcin G.", "text" => "Dobre zarówno na zimę, jak i na lato."),
    array("name" => "Krystian H.", "text" => "Nie wyglądają na zużyte nawet po miesiącu."),
    array("name" => "Tymon A.", "text" => "Krój pasuje idealnie."),
    array("name" => "Fabian S.", "text" => "Wygodne nawet podczas długiej jazdy."),
    array("name" => "Damian K.", "text" => "Najlepsze bokserki, jakie kupiłem."),
    array("name" => "Sebastian M.", "text" => "Materiał klasy premium."),
    array("name" => "Zbigniew U.", "text" => "Nie uciskają ud, co zawsze było problemem."),
    array("name" => "Krzysztof B.", "text" => "Trzymają wszystko na miejscu."),
    array("name" => "Dawid P.", "text" => "Brak dyskomfortu nawet przy długim noszeniu."),
    array("name" => "Tymoteusz L.", "text" => "Idealne do codziennego użytku."),
    array("name" => "Oskar R.", "text" => "Nie podciągają się, cały dzień leżą idealnie."),
    array("name" => "Sławomir I.", "text" => "Bokserki o najwyższym komforcie."),
    array("name" => "Janek S.", "text" => "Świetnie balansują wygodę i podparcie."),
    array("name" => "Mateusz V.", "text" => "Brak śliskiego uczucia, wszystko naturalne."),
    array("name" => "Adam P.", "text" => "Zachowują kształt, nie rozciągają się."),
    array("name" => "Julian D.", "text" => "Materiał niesamowicie delikatny."),
    array("name" => "Maciej H.", "text" => "Guma nie pęka i nie zwija się."),
    array("name" => "Wiktor C.", "text" => "Jakość znacznie lepsza niż się spodziewałem."),
    array("name" => "Borys K.", "text" => "Nie wiedziałem, że bokserki mogą być aż tak dobre."),
    array("name" => "Tomasz U.", "text" => "Świetna wentylacja i uczucie świeżości."),
    array("name" => "Ludwik F.", "text" => "Brak obtarć nawet przy długim chodzeniu."),
    array("name" => "Marek T.", "text" => "Wygodne nawet w bardzo ciepłe dni."),
    array("name" => "Wiktor P.", "text" => "Najlepsze bokserki dla mojej sylwetki."),
    array("name" => "Adrian S.", "text" => "Brak potu, materiał świetnie oddycha."),
    array("name" => "Harold J.", "text" => "Bardzo lekkie i przewiewne."),
    array("name" => "Noah M.", "text" => "Trzymają kolor, nie blakną."),
    array("name" => "Tomasz C.", "text" => "Bardzo wygodne nawet pod jeansami."),
    array("name" => "Walenty L.", "text" => "Nie spodziewałem się takiego komfortu."),
    array("name" => "Dariusz S.", "text" => "Naprawdę świetne bokserki."),
    array("name" => "Leon N.", "text" => "Noszę je codziennie od zakupu."),
    array("name" => "Michał J.", "text" => "Brak fałd i skręcania."),
    array("name" => "Dawid P.", "text" => "Spodziewałem się mniej, dostałem więcej."),
    array("name" => "Franciszek S.", "text" => "Świetne nawet podczas jazdy na rowerze."),
    array("name" => "Erik R.", "text" => "Z czystym sumieniem polecam."),
    array("name" => "Sylwester M.", "text" => "Materiał się nie mechaci."),
    array("name" => "Zbigniew G.", "text" => "Nie podciągają się do góry – idealnie."),
    array("name" => "Dariusz S.", "text" => "Idealne dla wrażliwej skóry."),
    array("name" => "Grzegorz P.", "text" => "Guma nie zostawia śladów."),
    array("name" => "Bartosz T.", "text" => "Pełne pochwały za komfort."),
    array("name" => "Alan F.", "text" => "Te bokserki to prawdziwy game-changer."),
    array("name" => "Stanisław L.", "text" => "Materiał szybko schnie."),
    array("name" => "Marcin Ż.", "text" => "Nie marszczą się pod spodniami."),
    array("name" => "Władysław Ś.", "text" => "Brak nieprzyjemnych zapachów nawet po całym dniu."),
    array("name" => "Łukasz R.", "text" => "W końcu bokserki, które leżą idealnie."),
    array("name" => "Filip U.", "text" => "Łatwe w praniu, nie tracą kształtu."),
    array("name" => "Borys K.", "text" => "Miękkie i bardzo trwałe."),
    array("name" => "Adam X.", "text" => "Najlepsze w tym przedziale cenowym."),
    array("name" => "Bruno V.", "text" => "Naprawdę się nie podwijają."),
    array("name" => "Andrzej K.", "text" => "Jestem bardzo zadowolony z materiału."),
    array("name" => "Szymon B.", "text" => "Nie podrażniają skóry – ogromny plus."),
    array("name" => "Kevin S.", "text" => "Super wygodne, noszę je codziennie."),
    array("name" => "Maciej P.", "text" => "Naprawdę topowe odczucie."),
    array("name" => "Marcin V.", "text" => "Po miesiącu nadal jak nowe."),
    array("name" => "Oskar L.", "text" => "Solidne, a jednocześnie elastyczne."),
    array("name" => "Dawid J.", "text" => "Nie uciskają nawet podczas ćwiczeń."),
    array("name" => "Krzysztof U.", "text" => "Po prostu perfekcyjne."),
    array("name" => "Sven M.", "text" => "Guma się nie zwija – świetna robota."),
    array("name" => "Robert P.", "text" => "Jedne z najwygodniejszych bokserek jakie nosiłem."),
    array("name" => "Karol B.", "text" => "Zdecydowanie polecam."),
    array("name" => "Tomasz S.", "text" => "Materiał, który naprawdę oddycha."),
    array("name" => "Tomasz K.", "text" => "Świetne również do sportu."),
    array("name" => "Dawid Z.", "text" => "Nie mam żadnych zastrzeżeń."),
    array("name" => "Daniel F.", "text" => "War­te każdej złotówki."),
    array("name" => "Mirosław K.", "text" => "Noszę je codziennie – idealne."),
    array("name" => "Sebastian R.", "text" => "Bez zarzutu. Kupuję ponownie.")
);
?>
